### ISSUE TITLE
Cannot see multi-line changes for add lines

### ISSUE THREAD

**Issue by eudaimos** [mark-hahn/git-diff-popup#3] opened 2015-05-25 14:21 UTC
Works well on single-line changes, but multi-line changes seem to show what would be the lines, but they are so tiny as to not be legible beyond looking like small gray lines

![screenshot 2015-05-25 07 19 48](https://cloud.githubusercontent.com/assets/835690/7798427/9c882820-02ae-11e5-8d82-b3fe88e2db6e.jpg)

**Comment by mark-hahn** [comment] 2015-05-25 17:15
Are you running in 1.0 preview?  I'm just starting to work on 1.0 styling
now.

In any case, thanks for the report and I should have it fixed soon.

**Comment by mark-hahn** [comment] 2015-05-25 21:57
I just did a semi-major rewrite to fix all the deprecations.  This was just released as 1.0.4.  I tested in 1.0 mode and with a dark theme and couldn't repeat the problem.

Let me know if the problem is fixed for you.  If not then please give me all your version info and what theme that is.  Also try it with a different theme.

**Comment by eudaimos** [comment] 2015-05-26 03:44
Will do @mark-hahn it's updating now

**Comment by mark-hahn** [comment] 2015-05-30 21:33
I'm pretty sure this is fixed.  Let me know if I'm wrong and I'll reopen this issue.

**Closed as completed by mark-hahn** 2015-05-30 21:33 UTC
Labels: bug, help wanted
